// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

/**
 * AI tool policy: for every API operation, whether the AI assistant may call
 * it, on which surface, and with which arguments filled by the server.
 *
 * - `never` (N): not a tool on any surface. The default for every new
 *   operation: settings and secrets, API keys, auth and MFA, users and
 *   permissions, the AI endpoints themselves, the simulator and OCTT, portal
 *   routes, webhooks, imports and exports, file transfers, and every write
 *   that moves money (payments, refunds, invoices, pricing, billing, free
 *   vend) or changes station security (credentials, certificates, network
 *   profiles, configuration variables, firmware).
 * - `read` (R): a GET the chatbot may call without asking.
 * - `write` (W): a POST, PUT, PATCH or DELETE the chatbot may propose. It
 *   runs only after the user confirms it (confirmation card and nonce).
 * - `supportRead(pins)`: a read the chatbot may call freely and the support
 *   assist surface may call only with the case's own ids. A pin fills the
 *   argument from the case being assisted: `case.id`, `case.stationId` and
 *   `case.driverId` are set by the server and hidden from the model;
 *   `case.sessionIds` limits the argument to the case's linked sessions.
 *   The support surface has no other tools and never a write.
 * - `omit`: arguments the model never sees or sends (station passwords).
 * - `redactedFields`: secret response fields of an exposed tool, listed so
 *   the schema gate accepts them. The redactor drops every secret-shaped
 *   field at run time; listing one here records that it was reviewed.
 *
 * The tool codegen (`generate-ai-tools.ts`) fails when an operation has no
 * entry, an entry names no operation, an exposure does not match the HTTP
 * method, or an exposed tool has a secret-shaped request or response field.
 * The unit tests (TC-AI-T-01, TC-AI-T-02, TC-AI-T-10, TC-AI-R-01) check the
 * committed catalog the same way. Each route still enforces its own RBAC and
 * site scope: tools run through `app.inject` as the user.
 */

export const AI_SURFACES = ['chatbot', 'support'] as const;
export type AiSurface = (typeof AI_SURFACES)[number];

export type ToolExposure = 'never' | 'read' | 'write';

/** Where a support-surface argument comes from. */
export const CASE_PINS = ['case.id', 'case.stationId', 'case.driverId', 'case.sessionIds'] as const;
export type CasePin = (typeof CASE_PINS)[number];

export interface ToolPolicy {
  exposure: ToolExposure;
  /** The chatbot surface offers the tool. */
  chatbot: boolean;
  /** The support assist surface offers the tool, with these arguments pinned to the case. */
  support: { pins: Readonly<Record<string, CasePin>> } | null;
  /** Arguments removed from the tool: the model never sees or sends them. */
  omit: readonly string[];
  /** Secret response fields the redactor drops, reviewed (see above). */
  redactedFields: readonly string[];
}

const N: ToolPolicy = {
  exposure: 'never',
  chatbot: false,
  support: null,
  omit: [],
  redactedFields: [],
};
const R: ToolPolicy = { ...N, exposure: 'read', chatbot: true };
const W: ToolPolicy = { ...N, exposure: 'write', chatbot: true };

function supportRead(
  pins: Record<string, CasePin>,
  options: { redactedFields?: readonly string[] } = {},
): ToolPolicy {
  return { ...R, support: { pins }, redactedFields: options.redactedFields ?? [] };
}

function write(options: { omit: readonly string[] }): ToolPolicy {
  return { ...W, omit: options.omit };
}

/** Keyed by OpenAPI operationId, grouped by tag. */
export const AI_TOOL_POLICY: Readonly<Record<string, ToolPolicy>> = {
  // AI Assistant
  confirmAiAction: N,
  confirmAssistantAttachment: N,
  createAiConversation: N,
  deleteAiConversation: N,
  deleteAssistantAttachment: N,
  getAiAssistantStatus: N,
  getAiConversation: N,
  getAssistantAttachmentDownloadUrl: N,
  listAiConversations: N,
  rejectAiAction: N,
  requestAssistantAttachmentUpload: N,
  sendAiMessage: N,
  updateAiConversation: N,
  // API Keys
  createApiKey: N,
  listApiKeys: N,
  revokeApiKey: N,
  updateApiKey: N,
  // Access Logs
  createAccessLog: N,
  listAccessLogs: R,
  listWorkerLogs: R,
  // Audit
  listAudit: R,
  listEntityAudit: R,
  // CSS Actions
  css_authorize: N,
  css_clearFault: N,
  css_comeOnline: N,
  css_evFull: N,
  css_goOffline: N,
  css_injectFault: N,
  css_plugIn: N,
  css_powerCycle: N,
  css_resumeCharging: N,
  css_startCharging: N,
  css_stopCharging: N,
  css_suspendCharging: N,
  css_unplug: N,
  // CSS Management
  createCssStation: N,
  deleteCssStation: N,
  disableCssStation: N,
  enableCssStation: N,
  getCssStation: N,
  listCssStations: N,
  updateCssStation: N,
  // CSS OCPP 1.6 Actions
  css_v16_sendAuthorize: N,
  css_v16_sendBootNotification: N,
  css_v16_sendDataTransfer: N,
  css_v16_sendDiagnosticsStatusNotification: N,
  css_v16_sendFirmwareStatusNotification: N,
  css_v16_sendHeartbeat: N,
  css_v16_sendMeterValues: N,
  css_v16_sendStartTransaction: N,
  css_v16_sendStatusNotification: N,
  css_v16_sendStopTransaction: N,
  // CSS OCPP 2.1 Actions
  css_v21_createPncEv: N,
  css_v21_installPncContract: N,
  css_v21_sendAuthorize: N,
  css_v21_sendBatterySwap: N,
  css_v21_sendBootNotification: N,
  css_v21_sendClearedChargingLimit: N,
  css_v21_sendDataTransfer: N,
  css_v21_sendFirmwareStatusNotification: N,
  css_v21_sendGet15118EVCertificate: N,
  css_v21_sendGetCertificateChainStatus: N,
  css_v21_sendGetCertificateStatus: N,
  css_v21_sendGetTransactionStatus: N,
  css_v21_sendHeartbeat: N,
  css_v21_sendLogStatusNotification: N,
  css_v21_sendMeterValues: N,
  css_v21_sendNotifyAllowedEnergyTransfer: N,
  css_v21_sendNotifyChargingLimit: N,
  css_v21_sendNotifyCustomerInformation: N,
  css_v21_sendNotifyDERAlarm: N,
  css_v21_sendNotifyDERStartStop: N,
  css_v21_sendNotifyDisplayMessages: N,
  css_v21_sendNotifyEVChargingNeeds: N,
  css_v21_sendNotifyEVChargingSchedule: N,
  css_v21_sendNotifyEvent: N,
  css_v21_sendNotifyMonitoringReport: N,
  css_v21_sendNotifyPeriodicEventStream: N,
  css_v21_sendNotifyPriorityCharging: N,
  css_v21_sendNotifyReport: N,
  css_v21_sendNotifySettlement: N,
  css_v21_sendPublishFirmwareStatusNotification: N,
  css_v21_sendPullDynamicScheduleUpdate: N,
  css_v21_sendReportChargingProfiles: N,
  css_v21_sendReportDERControl: N,
  css_v21_sendReservationStatusUpdate: N,
  css_v21_sendSecurityEventNotification: N,
  css_v21_sendSignCertificate: N,
  css_v21_sendStatusNotification: N,
  css_v21_sendTransactionEvent: N,
  css_v21_sendVatNumberValidation: N,
  css_v21_startPncCharging: N,
  // Conformance
  getConformanceRunNeighbors: N,
  // Dashboard
  getDashboardCarbonStats: R,
  getDashboardFinancialStats: R,
  getDashboardOcppHealth: R,
  getDashboardSiteLocations: R,
  getDashboardSnapshot: R,
  getDashboardSnapshotAvailableDates: R,
  getDashboardSnapshotTrend: R,
  getDashboardUptime: R,
  listDashboardEnergyHistory: R,
  listDashboardPaymentBreakdown: R,
  listDashboardPeakUsage: R,
  listDashboardRevenueHistory: R,
  listDashboardSessionHistory: R,
  listDashboardStationStatus: R,
  listDashboardStats: R,
  listDashboardUtilization: R,
  // Display Messages
  clearDisplayMessage: W,
  createDisplayMessage: W,
  listDisplayMessages: R,
  refreshDisplayMessages: W,
  // Drivers
  addDriverPricingGroup: N,
  createDriver: W,
  createDriverPncContract: N,
  createDriverToken: W,
  createDriverVehicle: W,
  deleteDriver: W,
  deleteDriverVehicle: W,
  getDriver: supportRead({ id: 'case.driverId' }),
  getDriverNeighbors: N,
  getDriverPricingGroup: R,
  getDriverVehicle: R,
  inviteDriverToPortal: N,
  listDriverPncContracts: N,
  listDriverReservations: R,
  listDriverSessions: supportRead({ id: 'case.driverId' }),
  listDriverTokens: R,
  listDriverVehicles: R,
  listDrivers: R,
  lookupVehicles: R,
  removeDriverPricingGroup: N,
  revokePncContract: N,
  updateDriver: W,
  updateDriverVehicle: W,
  // Event Alert Rules
  createEventAlertRule: W,
  deleteEventAlertRule: W,
  listEventAlertRules: R,
  updateEventAlertRule: W,
  // Events
  streamEvents: N,
  // Fleet Operations
  cancelFirmwareCampaign: N,
  createConfigTemplate: W,
  createFirmwareCampaign: N,
  deleteConfigTemplate: W,
  deleteFirmwareCampaign: N,
  duplicateConfigTemplate: W,
  getConfigTemplate: R,
  getConfigTemplateFilterOptions: R,
  getConfigTemplatePushDetail: R,
  getFirmwareCampaign: N,
  getFirmwareCampaignFilterOptions: N,
  getStationConfigDrift: R,
  listConfigTemplateMatchingStations: R,
  listConfigTemplatePushes: R,
  listConfigTemplates: R,
  listFirmwareCampaignMatchingStations: N,
  listFirmwareCampaigns: N,
  pushConfigTemplate: W,
  startFirmwareCampaign: N,
  updateConfigTemplate: W,
  updateFirmwareCampaign: N,
  // Fleets
  addFleetDriver: W,
  addFleetPricingGroup: N,
  addFleetStation: W,
  cancelFleetReservation: W,
  createFleet: W,
  createFleetInvoice: N,
  createFleetReservation: W,
  deleteFleet: W,
  getFleet: R,
  getFleetCreditLimit: R,
  getFleetEnergyHistory: R,
  getFleetMetrics: R,
  getFleetNeighbors: N,
  getFleetPricingGroup: R,
  listAvailableFleetVehicles: R,
  listFleetDrivers: R,
  listFleetInvoices: R,
  listFleetReservations: R,
  listFleetSessions: R,
  listFleetStations: R,
  listFleetVehicles: R,
  listFleets: R,
  previewFleetInvoice: R,
  removeFleetDriver: W,
  removeFleetPricingGroup: N,
  removeFleetStation: W,
  updateFleet: W,
  updateFleetBilling: N,
  updateFleetBillingProfile: N,
  updateFleetCreditLimit: N,
  updateFleetDriverBilling: N,
  // Health
  getHealth: N,
  getVersion: N,
  // Invoices
  createAggregatedInvoice: N,
  createCreditNote: N,
  createSessionInvoice: N,
  downloadInvoice: N,
  downloadInvoicePdf: N,
  getInvoice: R,
  getInvoiceNeighbors: N,
  listInvoices: R,
  markInvoicePaid: N,
  sendInvoice: N,
  voidInvoice: N,
  // Load Management
  assignStationCircuit: W,
  createCircuit: W,
  createPanel: W,
  createUnmanagedLoad: W,
  deleteCircuit: W,
  deletePanel: W,
  deleteUnmanagedLoad: W,
  getPanel: R,
  getSiteLoadManagement: R,
  getSiteLoadManagementHistory: R,
  listCircuits: R,
  listPanels: R,
  listUnmanagedLoads: R,
  updateCircuit: W,
  updatePanel: W,
  updateStationLoadPriority: W,
  updateUnmanagedLoad: W,
  upsertSiteLoadManagement: W,
  // Local Auth List
  addLocalAuthTokens: W,
  listAvailableTokensForLocalAuth: R,
  listLocalAuthEntries: R,
  pushLocalAuthList: W,
  removeLocalAuthEntries: W,
  // Maintenance
  addMaintenanceStations: W,
  cancelSiteMaintenanceEvent: W,
  createSiteMaintenanceEvent: W,
  getSiteMaintenanceEvent: R,
  getSiteMaintenanceStationPreview: R,
  getSiteMaintenanceStatus: R,
  listMaintenanceEventStations: R,
  listSiteMaintenanceEvents: R,
  previewMaintenanceMessage: W,
  removeMaintenanceStations: W,
  updateSiteMaintenanceEvent: W,
  // NEVI
  createNeviExcludedDowntime: W,
  deleteNeviExcludedDowntime: W,
  listNeviExcludedDowntime: R,
  listNeviStationData: R,
  updateNeviExcludedDowntime: W,
  upsertNeviStationData: W,
  // Notifications
  deleteNotificationTemplate: W,
  deleteOcppEventSetting: W,
  getDriverEventSettings: R,
  getNotificationTemplate: R,
  getOcppEventSettings: R,
  getOcppEventTemplate: R,
  listEventTypes: R,
  listNotifications: R,
  previewNotificationTemplate: W,
  sendTestNotification: N,
  updateDriverEventSettings: W,
  updateOcppEventSettings: W,
  upsertNotificationTemplate: W,
  // OCPI
  createOcpiCreditCdr: N,
  createOcpiPartner: N,
  createOcpiTariffMapping: N,
  deleteOcpiPartner: N,
  deleteOcpiTariffMapping: N,
  getOcpiLocation: R,
  getOcpiPartner: R,
  getOcpiPartnerNeighbors: N,
  getOcpiTariffMapping: R,
  listOcpiCdrs: R,
  listOcpiLocations: R,
  listOcpiPartners: R,
  listOcpiSessions: R,
  listOcpiSyncLog: R,
  listOcpiTariffMappings: R,
  registerOcpiPartner: N,
  syncOcpiPartnerModule: N,
  updateOcpiLocation: N,
  updateOcpiPartner: N,
  updateOcpiTariffMapping: N,
  // OCPP
  getOcppSchema: R,
  // OCPP 1.6 Commands
  getOcppV16CommandSchema: R,
  ocppv16_CancelReservation: W,
  ocppv16_CertificateSigned: N,
  ocppv16_ChangeAvailability: W,
  ocppv16_ChangeConfiguration: N,
  ocppv16_ClearCache: W,
  ocppv16_ClearChargingProfile: W,
  ocppv16_DataTransfer: N,
  ocppv16_DeleteCertificate: N,
  ocppv16_ExtendedTriggerMessage: W,
  ocppv16_GetCompositeSchedule: W,
  ocppv16_GetConfiguration: W,
  ocppv16_GetDiagnostics: N,
  ocppv16_GetInstalledCertificateIds: N,
  ocppv16_GetLocalListVersion: W,
  ocppv16_GetLog: N,
  ocppv16_InstallCertificate: N,
  ocppv16_RemoteStartTransaction: W,
  ocppv16_RemoteStopTransaction: W,
  ocppv16_ReserveNow: W,
  ocppv16_Reset: W,
  ocppv16_SendLocalList: W,
  ocppv16_SetChargingProfile: W,
  ocppv16_SignedUpdateFirmware: N,
  ocppv16_TriggerMessage: W,
  ocppv16_UnlockConnector: W,
  ocppv16_UpdateFirmware: N,
  // OCPP 2.1 Commands
  getOcppV21CommandSchema: R,
  ocppv21_AFRRSignal: W,
  ocppv21_AdjustPeriodicEventStream: W,
  ocppv21_CancelReservation: W,
  ocppv21_CertificateSigned: N,
  ocppv21_ChangeAvailability: W,
  ocppv21_ChangeTransactionTariff: N,
  ocppv21_ClearCache: W,
  ocppv21_ClearChargingProfile: W,
  ocppv21_ClearDERControl: W,
  ocppv21_ClearDisplayMessage: W,
  ocppv21_ClearTariffs: N,
  ocppv21_ClearVariableMonitoring: W,
  ocppv21_ClosePeriodicEventStream: W,
  ocppv21_CostUpdated: N,
  ocppv21_CustomerInformation: N,
  ocppv21_DataTransfer: N,
  ocppv21_DeleteCertificate: N,
  ocppv21_GetBaseReport: W,
  ocppv21_GetChargingProfiles: W,
  ocppv21_GetCompositeSchedule: W,
  ocppv21_GetDERControl: W,
  ocppv21_GetDisplayMessages: W,
  ocppv21_GetInstalledCertificateIds: N,
  ocppv21_GetLocalListVersion: W,
  ocppv21_GetLog: N,
  ocppv21_GetMonitoringReport: W,
  ocppv21_GetPeriodicEventStream: W,
  ocppv21_GetReport: W,
  ocppv21_GetTariffs: W,
  ocppv21_GetTransactionStatus: W,
  ocppv21_GetVariables: W,
  ocppv21_InstallCertificate: N,
  ocppv21_OpenPeriodicEventStream: W,
  ocppv21_PublishFirmware: N,
  ocppv21_RequestBatterySwap: W,
  ocppv21_RequestStartTransaction: W,
  ocppv21_RequestStopTransaction: W,
  ocppv21_ReserveNow: W,
  ocppv21_Reset: W,
  ocppv21_SendLocalList: W,
  ocppv21_SetChargingProfile: W,
  ocppv21_SetDERControl: W,
  ocppv21_SetDefaultTariff: N,
  ocppv21_SetDisplayMessage: W,
  ocppv21_SetMonitoringBase: W,
  ocppv21_SetMonitoringLevel: W,
  ocppv21_SetNetworkProfile: N,
  ocppv21_SetVariableMonitoring: W,
  ocppv21_SetVariables: N,
  ocppv21_TriggerMessage: W,
  ocppv21_UnlockConnector: W,
  ocppv21_UnpublishFirmware: N,
  ocppv21_UpdateDynamicSchedule: W,
  ocppv21_UpdateFirmware: N,
  ocppv21_UsePriorityCharging: W,
  ocppv21_VatNumberValidation: N,
  // OCTT
  createOcttRun: N,
  getOcttRun: N,
  getOcttRunSummary: N,
  listOcttRuns: N,
  // Payments
  captureSessionPayment: N,
  continueDriverPaymentMethodSetup: N,
  createAdyenWebhook: N,
  createDriverPaymentMethod: N,
  createDriverSetupIntent: N,
  createSitePayoutAccount: N,
  createSitePayoutInvite: N,
  createStripeWebhook: N,
  deleteDriverPaymentMethod: N,
  deleteSitePaymentConfig: N,
  getAdyenSettings: N,
  getAdyenWebhook: N,
  getPaymentSettings: N,
  getSessionPayment: supportRead({ id: 'case.sessionIds' }),
  getSitePaymentConfig: R,
  getSitePayoutAccount: N,
  getStripeSettings: N,
  getStripeWebhookSetup: N,
  listDriverPaymentMethods: R,
  listPayments: R,
  listReconciliationRuns: R,
  listReservationFeePayments: R,
  listSitePaymentConfigs: R,
  preAuthorizeSessionPayment: N,
  refreshSitePayoutAccount: N,
  refundReservationFeePayment: N,
  refundSessionPayment: N,
  retryPaymentCapture: N,
  runReconciliation: N,
  setDefaultDriverPaymentMethod: N,
  startAdHocPayment: N,
  submitDriverPaymentMethodSetup: N,
  testAdyenConnection: N,
  testStripeConnection: N,
  updateAdyenSettings: N,
  updatePaymentSettings: N,
  updateStripeSettings: N,
  upsertSitePaymentConfig: N,
  // PnC
  createPncLocalCa: N,
  deletePncCaCertificate: N,
  getPncLocalCa: N,
  getPncSettings: N,
  listPncCaCertificates: N,
  listPncCsrRequests: N,
  listPncStationCertificates: N,
  refreshPncRootCertificates: N,
  rejectPncCsrRequest: N,
  signPncCsrRequest: N,
  testPncProvider: N,
  updatePncSettings: N,
  uploadPncCaCertificate: N,
  // Portal Access Logs
  createPortalAccessLog: N,
  // Portal Auth
  portalActivate: N,
  portalAttestChallenge: N,
  portalAttestRegister: N,
  portalForgotPassword: N,
  portalGetMe: N,
  portalLogin: N,
  portalLogout: N,
  portalRefreshToken: N,
  portalRegister: N,
  portalResendMfa: N,
  portalResendVerification: N,
  portalResetPassword: N,
  portalVerifyEmail: N,
  portalVerifyMfa: N,
  // Portal Chargers
  portalCancelReservation: N,
  portalCheckConnectorStatus: N,
  portalCreateReservation: N,
  portalGetChargerEvse: N,
  portalGetChargerPricing: N,
  portalGetLocationDetail: N,
  portalGetLocationImageDownloadUrl: N,
  portalGetLocationImages: N,
  portalGetLocationPopularTimes: N,
  portalGetMapConfig: N,
  portalGetReservation: N,
  portalGetStationDetail: N,
  portalListActiveSessions: N,
  portalListNearbyChargers: N,
  portalListReservations: N,
  portalSearchChargers: N,
  portalStartCharging: N,
  portalStopSession: N,
  portalStreamStationEvents: N,
  // Portal Driver
  portalAddFavorite: N,
  portalAddStationWatch: N,
  portalChangePassword: N,
  portalCheckFavorite: N,
  portalCheckStationWatch: N,
  portalConfirmMfa: N,
  portalDisableMfa: N,
  portalGetMfaStatus: N,
  portalGetNotificationPreferences: N,
  portalListFavorites: N,
  portalListStationWatches: N,
  portalRemoveFavorite: N,
  portalRemoveStationWatch: N,
  portalSetupMfa: N,
  portalUpdateNotificationPreferences: N,
  portalUpdateProfile: N,
  // Portal Events
  portalStreamEvents: N,
  // Portal Guest
  guestCheckConnectorStatus: N,
  portalGuestContinuePayment: N,
  portalGuestGetChargerConfig: N,
  portalGuestGetEnergyHistory: N,
  portalGuestGetPowerHistory: N,
  portalGuestGetSessionStatus: N,
  portalGuestStartCharging: N,
  portalGuestStopCharging: N,
  portalGuestValidateQrCode: N,
  // Portal Notifications
  portalGetUnreadNotificationCount: N,
  portalListNotifications: N,
  portalMarkNotificationsRead: N,
  portalRegisterPushToken: N,
  portalUnregisterPushToken: N,
  // Portal Payments
  portalContinuePaymentMethodSetup: N,
  portalCreateEphemeralKey: N,
  portalCreateSetupIntent: N,
  portalDeletePaymentMethod: N,
  portalGetPaymentProvider: N,
  portalListPaymentMethods: N,
  portalSavePaymentMethod: N,
  portalSetDefaultPaymentMethod: N,
  portalSubmitPaymentMethodSetup: N,
  // Portal Payout Onboarding
  portalPayoutOnboardingLink: N,
  portalPayoutOnboardingStatus: N,
  // Portal Roaming
  portalSearchRoamingChargers: N,
  portalStartRoamingSession: N,
  // Portal Sessions
  portalGetMonthlyStatement: N,
  portalGetMonthlySummary: N,
  portalGetSession: N,
  portalGetSessionEnergyHistory: N,
  portalGetSessionPowerHistory: N,
  portalListSessions: N,
  portalSetSessionVehicle: N,
  // Portal Support
  portalConfirmAttachment: N,
  portalCreateSupportCase: N,
  portalCreateSupportMessage: N,
  portalGetAttachmentDownloadUrl: N,
  portalGetSupportCase: N,
  portalListSupportCases: N,
  portalRequestAttachmentUploadUrl: N,
  // Portal Tokens
  portalCreateToken: N,
  portalDeleteToken: N,
  portalListTokens: N,
  portalUpdateToken: N,
  // Portal Vehicles
  portalCreateVehicle: N,
  portalDeleteVehicle: N,
  portalGetVehicleEfficiency: N,
  portalListVehicles: N,
  portalLookupVehicles: N,
  // Pricing
  bulkCreatePricingHolidays: N,
  createGroupTariff: N,
  createPricingGroup: N,
  createPricingHoliday: N,
  deleteGroupTariff: N,
  deletePricingGroup: N,
  deletePricingHoliday: N,
  getGroupTariff: R,
  getPricingGroup: R,
  getPricingGroupNeighbors: N,
  getPricingGroupSchedule: R,
  getStationActiveTariff: R,
  listAllTariffs: R,
  listGroupTariffs: R,
  listPricingAudit: R,
  listPricingGroups: R,
  listPricingHolidays: R,
  updateGroupTariff: N,
  updatePricingGroup: N,
  // Reports
  createReportSchedule: W,
  deleteReport: W,
  deleteReportSchedule: W,
  downloadReport: N,
  exportCarbonReport: N,
  generateReport: W,
  getCarbonReport: R,
  getReport: R,
  listReportSchedules: R,
  listReportTypes: R,
  listReports: R,
  runReportScheduleNow: W,
  updateReportSchedule: W,
  // Reservations
  cancelReservation: W,
  createReservation: W,
  getReservation: R,
  getReservationNeighbors: N,
  listReservationAudit: R,
  listReservationCommands: R,
  listReservations: R,
  reassignReservation: W,
  updateReservation: W,
  // Sessions
  // The guest portal's session token is dropped by the redactor.
  getSession: supportRead({ id: 'case.sessionIds' }, { redactedFields: ['sessionToken'] }),
  getSessionNeighbors: N,
  listSessionMeterValues: supportRead({ id: 'case.sessionIds' }),
  listSessionTransactionEvents: supportRead({ id: 'case.sessionIds' }),
  listSessions: R,
  rebillSession: N,
  // Settings
  deleteSetting: N,
  flushResponseCache: N,
  getAiDefaults: N,
  getCarbonFactor: N,
  getPortalBranding: N,
  getPortalContent: N,
  getPortalFeatures: N,
  getPublicSecuritySettings: N,
  getS3Status: N,
  getSecuritySettings: N,
  getSetting: N,
  getSsoSettings: N,
  getSystemInfo: N,
  listCarbonFactors: N,
  listSettings: N,
  listStationMessageTemplates: N,
  previewEmailWrapper: N,
  previewStationMessageTemplate: N,
  resetStationMessageTemplate: N,
  ssoCallback: N,
  ssoLogin: N,
  testS3Connection: N,
  updateMfaSettings: N,
  updateRecaptchaSettings: N,
  updateS3Settings: N,
  updateSetting: N,
  updateSsoSettings: N,
  updateStationMessageTemplate: N,
  upsertSetting: N,
  // Sites
  addSitePricingGroup: N,
  createSite: W,
  createSiteElectricityRate: W,
  deleteSite: W,
  deleteSiteElectricityRate: W,
  exportSiteTemplate: N,
  exportSites: N,
  getSite: R,
  getSiteCarbonRegion: R,
  getSiteEnergyHistory: R,
  getSiteFilterOptions: R,
  getSiteLayout: R,
  getSiteMeterValues: R,
  getSiteMetrics: R,
  getSiteNeighbors: N,
  getSitePopularTimes: R,
  getSitePricingGroup: R,
  getSiteRevenueHistory: R,
  importSites: N,
  listSiteElectricityRates: R,
  listSiteSessions: R,
  listSiteStations: R,
  listSites: R,
  removeSitePricingGroup: N,
  toggleSiteFreeVend: N,
  updateSite: W,
  updateSiteCarbonRegion: W,
  updateSiteElectricityRate: W,
  updateSiteLayout: W,
  // Smart Charging
  clearChargingProfileTemplate: W,
  createChargingProfileTemplate: W,
  deleteChargingProfileTemplate: W,
  duplicateChargingProfileTemplate: W,
  getChargingProfilePushDetail: R,
  getChargingProfileTemplate: R,
  getSmartChargingFilterOptions: R,
  listChargingProfileMatchingStations: R,
  listChargingProfilePushes: R,
  listChargingProfileTemplates: R,
  pushChargingProfileTemplate: W,
  updateChargingProfileTemplate: W,
  // Stations
  acknowledgeEventAlert: W,
  addStationConnector: W,
  addStationEvse: W,
  addStationPricingGroup: N,
  approveStation: W,
  checkStationWebPaymentSupport: N,
  clearStationChargingProfiles: W,
  confirmRealStation: W,
  confirmStationImageUpload: N,
  createStation: write({ omit: ['password', 'securityProfile'] }),
  createStationMonitoringRule: W,
  deleteStation: W,
  deleteStationCertificate: N,
  deleteStationConnector: W,
  deleteStationEvse: W,
  deleteStationImage: W,
  deleteStationMonitoringRule: W,
  disableStationWebPayments: N,
  enableStationWebPayments: N,
  getConfigTemplateNeighbors: N,
  getFirmwareCampaignNeighbors: N,
  getSmartChargingTemplateNeighbors: N,
  getStation: supportRead({ id: 'case.stationId' }),
  getStationCompositeSchedule: W,
  getStationEnergyHistory: R,
  getStationImageDownloadUrl: N,
  getStationImageUploadUrl: N,
  getStationMeterValues: R,
  getStationMetrics: R,
  getStationNeighbors: N,
  getStationOcppLogs: supportRead({ id: 'case.stationId' }),
  getStationPopularTimes: R,
  getStationPricingGroup: R,
  getStationRevenueHistory: R,
  getStationSecurityLogs: R,
  getStationUptimeHistory: R,
  getStationWebPayments: N,
  installStationCertificate: N,
  listStationCertificates: R,
  listStationChargingProfiles: R,
  listStationConnectors: supportRead({ id: 'case.stationId' }),
  listStationEvChargingNeeds: R,
  listStationEventAlerts: R,
  listStationEvents: supportRead({ id: 'case.stationId' }),
  listStationFirmwareHistory: N,
  listStationImages: R,
  listStationMeterValues: R,
  listStationMonitoringRules: R,
  listStationSecurityEvents: R,
  listStationSessions: R,
  listStationVariables: R,
  listStations: R,
  pushStationChargingProfile: W,
  pushStationConfiguration: W,
  queryStationCertificates: N,
  refreshEvseConnectorStatus: W,
  refreshStationChargingProfiles: W,
  refreshStationConfigurations: W,
  rejectStation: W,
  removeStationPricingGroup: N,
  reorderStationImages: W,
  rotateStationCredentials: N,
  setMainStationImage: W,
  setStationCredentials: N,
  stopActiveEvseSession: W,
  unblockStation: W,
  updateStation: write({ omit: ['password', 'securityProfile'] }),
  updateStationEvse: W,
  updateStationImage: W,
  // Support Cases
  addSupportCaseMessage: W,
  confirmSupportCaseAttachment: N,
  createSupportCase: W,
  deleteSupportCaseAttachment: N,
  getSupportAttachmentStorage: N,
  getSupportCase: supportRead({ id: 'case.id' }),
  getSupportCaseAttachmentDownloadUrl: N,
  getSupportCaseAttachmentUploadUrl: N,
  getSupportCaseNeighbors: N,
  getUnreadSupportCaseCount: R,
  listSupportCases: R,
  markSupportCaseRead: W,
  refundSupportCaseSession: N,
  supportCaseAiAssist: N,
  updateSupportCase: W,
  // Tokens
  bulkSetTokensActive: W,
  createToken: W,
  deleteToken: W,
  exportTokens: N,
  getToken: R,
  getTokenFilterOptions: R,
  getTokenNeighbors: N,
  importTokens: N,
  listAuthorizeAttempts: R,
  listTokenSessions: R,
  listTokens: R,
  updateToken: W,
  // Transactions
  getTransactionById: R,
  getTransactionsBySession: R,
  listTransactions: R,
  // Users
  changePassword: N,
  confirmMfa: N,
  createUser: N,
  deleteMyChatbotAiConfig: N,
  deleteMySupportAiConfig: N,
  deleteUser: N,
  disableMfa: N,
  forceChangePassword: N,
  forgotPassword: N,
  getCurrentUser: N,
  getMfaStatus: N,
  getMyAiDefaults: N,
  getMyChatbotAiConfig: N,
  getMyPermissions: N,
  getMySupportAiConfig: N,
  getPermissionCatalog: N,
  getUser: R,
  getUserNeighbors: N,
  getUserNotificationPreferences: N,
  getUserPermissions: N,
  listRoles: R,
  listUsers: R,
  loginUser: N,
  logout: N,
  refreshToken: N,
  resendMfa: N,
  resendUserInvite: N,
  resetPassword: N,
  resetUserPassword: N,
  setupMfa: N,
  updateCurrentUser: N,
  updateMyChatbotAiConfig: N,
  updateMySupportAiConfig: N,
  updateUser: N,
  updateUserNotificationPreferences: N,
  updateUserPermissions: N,
  verifyMfa: N,
  // Webhooks
  handleAdyenWebhook: N,
  handleStripeWebhook: N,
};

/** The policy of an operation; an operation without an entry is never a tool. */
export function toolPolicy(operationId: string): ToolPolicy {
  return Object.prototype.hasOwnProperty.call(AI_TOOL_POLICY, operationId)
    ? (AI_TOOL_POLICY[operationId] ?? N)
    : N;
}

/** Whether `surface` offers the operation. */
export function surfaceOffers(policy: ToolPolicy, surface: AiSurface): boolean {
  if (policy.exposure === 'never') return false;
  return surface === 'chatbot' ? policy.chatbot : policy.support !== null;
}
