// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

// CSMS-initiated OCPP commands offered by the Advanced Command form of the
// station Commands tab, per OCPP version.

export const CSMS_ACTIONS = [
  'AdjustPeriodicEventStream',
  'AFRRSignal',
  'CancelReservation',
  'CertificateSigned',
  'ChangeAvailability',
  'ChangeTransactionTariff',
  'ClearCache',
  'ClearChargingProfile',
  'ClearDERControl',
  'ClearDisplayMessage',
  'ClearTariffs',
  'ClearVariableMonitoring',
  'ClosePeriodicEventStream',
  'CostUpdated',
  'CustomerInformation',
  'DataTransfer',
  'DeleteCertificate',
  'Get15118EVCertificate',
  'GetBaseReport',
  'GetCertificateChainStatus',
  'GetChargingProfiles',
  'GetCompositeSchedule',
  'GetDERControl',
  'GetDisplayMessages',
  'GetInstalledCertificateIds',
  'GetLocalListVersion',
  'GetLog',
  'GetMonitoringReport',
  'GetPeriodicEventStream',
  'GetReport',
  'GetTariffs',
  'GetVariables',
  'InstallCertificate',
  'OpenPeriodicEventStream',
  'PublishFirmware',
  'RequestBatterySwap',
  'RequestStartTransaction',
  'RequestStopTransaction',
  'ReserveNow',
  'Reset',
  'SendLocalList',
  'SetChargingProfile',
  'SetDERControl',
  'SetDefaultTariff',
  'SetDisplayMessage',
  'SetMonitoringBase',
  'SetMonitoringLevel',
  'SetNetworkProfile',
  'SetVariableMonitoring',
  'SetVariables',
  'TriggerMessage',
  'UnlockConnector',
  'UnpublishFirmware',
  'UpdateDynamicSchedule',
  'UpdateFirmware',
  'UsePriorityCharging',
] as const;

export const CSMS_ACTIONS_16 = [
  'CancelReservation',
  'ChangeAvailability',
  'ChangeConfiguration',
  'ClearCache',
  'ClearChargingProfile',
  'DataTransfer',
  'GetCompositeSchedule',
  'GetConfiguration',
  'GetDiagnostics',
  'GetLocalListVersion',
  'RemoteStartTransaction',
  'RemoteStopTransaction',
  'ReserveNow',
  'Reset',
  'SendLocalList',
  'SetChargingProfile',
  'TriggerMessage',
  'UnlockConnector',
  'UpdateFirmware',
] as const;
