// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

/**
 * OCPP 2.1 configurable component/variable mapping.
 * Sourced from docs/OCPP-2.1/Appendices_CSV_v2.1/dm_components_vars.csv.
 * Only includes controller components (configurable via SetVariables).
 */
export const OCPP_21_VARIABLES: Record<string, string[]> = {
  AlignedDataCtrlr: [
    'Available',
    'Enabled',
    'Interval',
    'Measurands',
    'SendDuringIdle',
    'SignReadings',
    'SignUpdatedReadings',
    'TxEndedInterval',
    'TxEndedMeasurands',
    'UpstreamInterval',
    'UpstreamMeasurands',
  ],
  AuthCacheCtrlr: ['Available', 'DisablePostAuthorize', 'Enabled', 'LifeTime', 'Policy', 'Storage'],
  AuthCtrlr: [
    'AdditionalInfoItemsPerMessage',
    'AuthorizeRemoteStart',
    'DisableRemoteAuthorization',
    'Enabled',
    'LocalAuthorizeOffline',
    'LocalPreAuthorize',
    'MasterPassGroupId',
    'OfflineTxForUnknownIdEnabled',
    'SupportedIdTokenType',
  ],
  ChargingStation: [
    'ActiveTransactionId',
    'AllowNewSessionsPendingFirmwareUpdate',
    'AvailabilityState',
    'Available',
    'Model',
    'SupplyPhases',
    'VendorName',
  ],
  Connector: [
    'AvailabilityState',
    'Available',
    'ChargeProtocol',
    'ConnectorType',
    'SlotStatus',
    'SupplyPhases',
  ],
  EVSE: [
    'ActiveTransactionId',
    'AllowReset',
    'AvailabilityState',
    'Available',
    'ChargingState',
    'DCInputPhaseControl',
    'DischargePower',
    'EvseId',
    'ISO15118EvseId',
    'Power',
    'SupplyPhases',
  ],
  ClockCtrlr: [
    'DateTime',
    'NextTimeOffsetTransitionDateTime',
    'NtpServerUri',
    'NtpSource',
    'TimeAdjustmentReportingThreshold',
    'TimeOffset',
    'TimeSource',
    'TimeZone',
  ],
  CustomizationCtrlr: ['CustomImplementationEnabled', 'CustomTriggers'],
  DeviceDataCtrlr: [
    'BytesPerMessage',
    'ConfigurationValueSize',
    'ItemsPerMessage',
    'ReportingValueSize',
    'ValueSize',
  ],
  DisplayMessageCtrlr: [
    'Available',
    'DisplayMessages',
    'Enabled',
    'Language',
    'SupportedFormats',
    'SupportedPriorities',
    'SupportedStates',
  ],
  ISO15118Ctrlr: [
    'CentralContractValidationAllowed',
    'CertificateStatusSource',
    'ContractCertificateInstallationEnabled',
    'ContractValidationOffline',
    'CountryName',
    'MaxPriceElements',
    'MaxScheduleEntries',
    'NotificationDelay',
    'OrganizationName',
    'PnCEnabled',
    'ProtocolSupported',
    'RequestMeteringReceipt',
    'RequestedEnergyTransferMode',
    'SeccId',
    'ServiceRenegotiationSupport',
    'SupportedProviders',
    'V2GCertificateInstallationEnabled',
  ],
  LocalAuthListCtrlr: [
    'Available',
    'BytesPerMessage',
    'DisablePostAuthorize',
    'Enabled',
    'Entries',
    'ItemsPerMessage',
    'Storage',
    'SupportsExpiryDateTime',
  ],
  MonitoringCtrlr: [
    'ActiveMonitoringBase',
    'ActiveMonitoringLevel',
    'Available',
    'BytesPerMessage',
    'Enabled',
    'ItemsPerMessage',
    'MaxPeriodicEventStreams',
    'MonitoringBase',
    'MonitoringLevel',
    'OfflineQueuingSeverity',
  ],
  OCPPCommCtrlr: [
    'ActiveNetworkProfile',
    'ExternalConfigChangeDate',
    'FieldLength',
    'FileTransferProtocols',
    'HeartbeatInterval',
    'MessageAttemptInterval',
    'MessageAttempts',
    'MessageTimeout',
    'NetworkConfigurationPriority',
    'NetworkProfileConnectionAttempts',
    'OfflineThreshold',
    'PublicKeyWithSignedMeterValue',
    'QueueAllMessages',
    'ResetRetries',
    'RetryBackOffRandomRange',
    'RetryBackOffRepeatTimes',
    'RetryBackOffWaitMinimum',
    'UnlockOnEVSideDisconnect',
    'WebSocketPingInterval',
  ],
  ReservationCtrlr: ['Available', 'Enabled', 'NonEvseSpecific'],
  SampledDataCtrlr: [
    'Available',
    'Enabled',
    'RegisterValuesWithoutPhases',
    'SignReadings',
    'SignStartedReadings',
    'SignUpdatedReadings',
    'TxEndedInterval',
    'TxEndedMeasurands',
    'TxStartedMeasurands',
    'TxUpdatedInterval',
    'TxUpdatedMeasurands',
    'UpstreamInterval',
    'UpstreamMeasurands',
  ],
  SecurityCtrlr: [
    'AdditionalRootCertificateCheck',
    'AllowSecurityProfileDowngrade',
    'BasicAuthPassword',
    'CertSigningRepeatTimes',
    'CertSigningWaitMinimum',
    'CertificateEntries',
    'Identity',
    'MaxCertificateChainSize',
    'OrganizationName',
    'SecurityProfile',
  ],
  SmartChargingCtrlr: [
    'ACPhaseSwitchingSupported',
    'Available',
    'ChargingProfilePersistence',
    'Enabled',
    'Entries',
    'ExternalConstraintsProfileDisallowed',
    'ExternalControlSignalsEnabled',
    'LimitChangeSignificance',
    'MaxExternalConstraintsId',
    'NotifyChargingLimitWithSchedules',
    'PeriodsPerSchedule',
    'Phases3to1',
    'ProfileStackLevel',
    'RateUnit',
    'SetpointPriority',
    'SupportedAdditionalPurposes',
    'SupportsDynamicProfiles',
    'SupportsEvseSleep',
    'SupportsLimitAtSoC',
    'SupportsMaxOfflineDuration',
    'SupportsRandomizedDelay',
    'SupportsUseLocalTime',
  ],
  TariffCostCtrlr: [
    'Available',
    'ConditionsSupported',
    'Currency',
    'Enabled',
    'HandleFailedTariff',
    'Interval',
    'MaxElements',
    'OfflineTariffFallbackMessage',
    'TariffFallbackMessage',
    'TotalCostFallbackMessage',
  ],
  TxCtrlr: [
    'AllowEnergyTransferResumption',
    'ChargingTime',
    'EVConnectionTimeOut',
    'EnergyTransferResumptionRandomRange',
    'MaxEnergyOnInvalidId',
    'ResumptionTimeout',
    'StopTxOnEVSideDisconnect',
    'StopTxOnInvalidId',
    'SupportedLimits',
    'TxBeforeAcceptedEnabled',
    'TxStartPoint',
    'TxStopPoint',
  ],
};

/**
 * OCPP 1.6 standard configuration keys.
 * Flat key/value model with no component hierarchy.
 */
export const OCPP_16_KEYS: string[] = [
  'AllowOfflineTxForUnknownId',
  'AuthorizationCacheEnabled',
  'AuthorizeRemoteTxRequests',
  'ClockAlignedDataInterval',
  'ConnectionTimeOut',
  'ConnectorPhaseRotation',
  'ConnectorPhaseRotationMaxLength',
  'GetConfigurationMaxKeys',
  'HeartbeatInterval',
  'LightIntensity',
  'LocalAuthorizeOffline',
  'LocalPreAuthorize',
  'MaxEnergyOnInvalidId',
  'MeterValueSampleInterval',
  'MeterValuesSampledData',
  'MeterValuesAlignedData',
  'MinimumStatusDuration',
  'NumberOfConnectors',
  'ResetRetries',
  'StopTransactionOnEVSideDisconnect',
  'StopTransactionOnInvalidId',
  'StopTxnAlignedData',
  'StopTxnSampledData',
  'SupportedFeatureProfiles',
  'TransactionMessageAttempts',
  'TransactionMessageRetryInterval',
  'UnlockConnectorOnEVSideDisconnect',
  'WebSocketPingInterval',
];
