// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

/**
 * Codegen: reads the OpenAPI spec and the AI tool policy
 * (`services/ai/tools/policy.ts`) and writes the tool catalog
 * (`services/ai/tools/catalog.ts`).
 *
 * Run via: npm run codegen:ai-tools
 *
 * It refuses to write a catalog when an operation has no policy entry, an
 * entry names no operation, an exposure does not match the HTTP method, or an
 * exposed tool has a secret-shaped argument or response field. The catalog
 * holds every operation id (for the coverage test) and the exposed tools only.
 */
import crypto from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import type {
  AiCatalogCategory,
  AiCatalogOperation,
  AiCatalogTool,
  AiToolMethod,
  JsonSchema,
} from './services/ai/tools/catalog-types.js';
import { AI_TOOL_POLICY, toolPolicy } from './services/ai/tools/policy.js';
import { exposedToolProblems, policyCoverageProblems } from './services/ai/tools/catalog-checks.js';
import {
  cleanSchema,
  collectFieldNames,
  toStrictSchema,
  withoutProperties,
} from './services/ai/tools/schema.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

process.env['API_PORT'] ??= '3001';
process.env['OCPP_PORT'] ??= '3003';
process.env['CORS_ORIGIN'] ??= 'http://localhost';
process.env['JWT_SECRET'] ??= `codegen-${crypto.randomUUID()}${crypto.randomUUID()}`;
process.env['SETTINGS_ENCRYPTION_KEY'] ??= crypto.randomBytes(32).toString('hex');

const catalogPath = resolve(__dirname, 'services', 'ai', 'tools', 'catalog.ts');

const HEADER = [
  '// Copyright (c) 2024-2026 EVtivity. All rights reserved.',
  '// SPDX-License-Identifier: BUSL-1.1',
  '',
  '// AUTO-GENERATED by generate-ai-tools.ts from the OpenAPI spec and tools/policy.ts. DO NOT EDIT.',
  '// Regenerate with: npm run codegen:ai-tools',
];

// The app imports the engine, which imports the catalog: write an empty one
// first so a missing or stale catalog cannot break the import below.
writeFileSync(
  catalogPath,
  [
    ...HEADER,
    '',
    "import type { AiCatalogCategory, AiCatalogOperation, AiCatalogTool } from './catalog-types.js';",
    '',
    'export const AI_OPERATIONS: readonly AiCatalogOperation[] = [];',
    'export const AI_TOOL_CATEGORIES: readonly AiCatalogCategory[] = [];',
    'export const AI_TOOL_CATALOG: readonly AiCatalogTool[] = [];',
    '',
  ].join('\n'),
);

// Imported after the stub is on disk.
const { buildApp } = await import('./app.js');

interface OpenApiParam {
  name: string;
  in: 'query' | 'path' | 'header' | 'cookie';
  required?: boolean;
  description?: string;
  schema?: JsonSchema;
}

interface OpenApiOperation {
  operationId?: string;
  summary?: string;
  tags?: string[];
  parameters?: OpenApiParam[];
  requestBody?: { content?: Record<string, { schema?: JsonSchema }> };
  responses?: Record<string, { content?: Record<string, { schema?: JsonSchema }> }>;
}

/** Category descriptions for the router. A tag without one uses its name. */
const TAG_DESCRIPTIONS: Record<string, string> = {
  Sites: 'Charging sites: list, details, create, update, delete, layout, electricity rates.',
  Stations:
    'Charging stations: list, details, EVSEs and connectors, status, events, OCPP logs, metrics, charging profiles, monitoring.',
  Sessions: 'Charging sessions: list, details, meter values, transaction events.',
  Dashboard: 'Dashboard statistics: counts, energy, revenue, uptime, utilization, peak usage.',
  Drivers: 'Drivers: list, details, create, update, tokens, vehicles, sessions.',
  Users: 'Operator users and roles (read only).',
  Tokens: 'Driver RFID tokens and authorize attempts.',
  Payments: 'Payment records and site payment configuration (read only).',
  Pricing: 'Pricing groups, tariffs and holidays (read only).',
  Reservations: 'Charging reservations.',
  Reports: 'Reports and report schedules.',
  'Support Cases': 'Support cases: list, details, messages.',
  Notifications: 'Notification templates, event settings and history.',
  'OCPP 2.1 Commands': 'Send OCPP 2.1 commands to a station (reset, start, stop, availability).',
  'OCPP 1.6 Commands': 'Send OCPP 1.6 commands to a station (reset, start, stop, availability).',
  OCPP: 'OCPP message schemas.',
  'Load Management': 'Site power management: limits, priorities, panels, circuits.',
  'Smart Charging': 'Charging profile templates.',
  Fleets: 'Fleets: members, stations, reservations.',
  'Fleet Operations': 'Config templates and their pushes.',
  Invoices: 'Invoices (read only).',
  OCPI: 'OCPI roaming: partners, locations, sessions, CDRs, tariffs (read only).',
  Transactions: 'Transaction event history.',
  'Access Logs': 'Operator access logs.',
  Audit: 'Audit history of entity changes.',
  Maintenance: 'Site maintenance events.',
  NEVI: 'NEVI station data and excluded downtime.',
  'Display Messages': 'Station display messages.',
  'Local Auth List': 'Station local authorization lists.',
  'Event Alert Rules': 'Event alert rules.',
};

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

function operationIdToToolName(operationId: string): string {
  return operationId.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
}

function jsonBodySchema(op: OpenApiOperation): JsonSchema | null {
  return op.requestBody?.content?.['application/json']?.schema ?? null;
}

function responseSchema(op: OpenApiOperation): unknown {
  const ok = op.responses?.['200'] ?? op.responses?.['201'];
  return ok?.content?.['application/json']?.schema;
}

interface BuiltTool {
  tool: AiCatalogTool | null;
  problems: string[];
}

function buildTool(
  operationId: string,
  method: AiToolMethod,
  path: string,
  op: OpenApiOperation,
): BuiltTool {
  const policy = toolPolicy(operationId);
  const problems: string[] = [];
  const properties: Record<string, JsonSchema> = {};
  const required: string[] = [];
  const pathParams: string[] = [];
  const queryParams: string[] = [];
  const bodyParams: string[] = [];

  const add = (name: string, schema: JsonSchema, isRequired: boolean): void => {
    if (name in properties) {
      problems.push(`${operationId}: argument '${name}' appears twice (path, query or body)`);
      return;
    }
    properties[name] = schema;
    if (isRequired) required.push(name);
  };

  for (const param of op.parameters ?? []) {
    if (param.in !== 'path' && param.in !== 'query') continue;
    const schema: JsonSchema = { ...(param.schema ?? { type: 'string' }) };
    if (param.description != null) schema['description'] = param.description;
    add(param.name, schema, param.in === 'path' || param.required === true);
    (param.in === 'path' ? pathParams : queryParams).push(param.name);
  }

  const body = jsonBodySchema(op);
  if (body != null) {
    const bodyProps = body['properties'];
    if (body['type'] !== 'object' || bodyProps == null || typeof bodyProps !== 'object') {
      problems.push(`${operationId}: the request body is not an object with properties`);
    } else {
      const bodyRequired = new Set((body['required'] as string[] | undefined) ?? []);
      for (const [name, schema] of Object.entries(bodyProps as Record<string, JsonSchema>)) {
        add(name, schema, bodyRequired.has(name));
        bodyParams.push(name);
      }
    }
  }

  for (const name of policy.omit) {
    if (!(name in properties)) problems.push(`${operationId}: omits unknown argument '${name}'`);
  }
  const plain = cleanSchema({ type: 'object', properties, required, additionalProperties: false });
  const validation = withoutProperties(plain, policy.omit);
  const strict = toStrictSchema(validation);
  const tool: AiCatalogTool = {
    name: operationIdToToolName(operationId),
    operationId,
    description: op.summary ?? operationId,
    category: op.tags?.[0] ?? 'Other',
    method,
    pathTemplate: path,
    pathParams,
    queryParams: queryParams.filter((p) => !policy.omit.includes(p)),
    bodyParams: bodyParams.filter((p) => !policy.omit.includes(p)),
    parameters: strict ?? validation,
    strict: strict !== null,
    validation,
    responseFields: [...collectFieldNames(responseSchema(op))].sort(),
  };
  return { tool, problems };
}

async function generate(): Promise<void> {
  const app = await buildApp({ logger: false });
  await app.ready();
  const spec = app.swagger() as { paths: Record<string, Record<string, OpenApiOperation>> };

  const operations: AiCatalogOperation[] = [];
  const tools: AiCatalogTool[] = [];
  const problems: string[] = [];

  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const m of METHODS) {
      const op = methods[m];
      if (op == null) continue;
      const method = m.toUpperCase() as AiToolMethod;
      if (op.operationId == null) {
        problems.push(`${method} ${path}: no operationId`);
        continue;
      }
      operations.push({ operationId: op.operationId, method, path });
      if (toolPolicy(op.operationId).exposure === 'never') continue;
      const built = buildTool(op.operationId, method, path, op);
      problems.push(...built.problems);
      if (built.tool != null) tools.push(built.tool);
    }
  }

  operations.sort((a, b) => a.operationId.localeCompare(b.operationId));
  tools.sort((a, b) => a.name.localeCompare(b.name));
  problems.push(...policyCoverageProblems(operations, AI_TOOL_POLICY));
  problems.push(...exposedToolProblems(tools, AI_TOOL_POLICY));

  await app.close();

  if (problems.length > 0) {
    console.error(`AI tool catalog not written, ${String(problems.length)} problem(s):`);
    for (const p of problems) console.error(`- ${p}`);
    process.exit(1);
  }

  const categories: AiCatalogCategory[] = [...new Set(tools.map((t) => t.category))]
    .sort()
    .map((tag) => ({ tag, description: TAG_DESCRIPTIONS[tag] ?? tag }));

  const source = [
    ...HEADER,
    `// ${String(operations.length)} operations, ${String(tools.length)} tools across ${String(categories.length)} categories`,
    '',
    "import type { AiCatalogCategory, AiCatalogOperation, AiCatalogTool } from './catalog-types.js';",
    '',
    '/** Every API operation, exposed or not (the policy coverage test reads it). */',
    `export const AI_OPERATIONS: readonly AiCatalogOperation[] = ${JSON.stringify(operations)};`,
    '',
    '/** Categories (OpenAPI tags) of the exposed tools, for the router. */',
    `export const AI_TOOL_CATEGORIES: readonly AiCatalogCategory[] = ${JSON.stringify(categories)};`,
    '',
    '/** The tools the policy exposes on some surface. */',
    `export const AI_TOOL_CATALOG: readonly AiCatalogTool[] = ${JSON.stringify(tools)};`,
    '',
  ].join('\n');

  const prettierConfig = (await resolveConfig(catalogPath)) ?? {};
  writeFileSync(catalogPath, await format(source, { ...prettierConfig, filepath: catalogPath }));
  console.log(
    `AI tool catalog: ${String(operations.length)} operations, ${String(tools.length)} tools -> ${catalogPath}`,
  );
}

generate().catch((err: unknown) => {
  console.error('Failed to generate the AI tool catalog:', err);
  process.exit(1);
});
