// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

import type { ParsedSchema } from '../parsers/schema-parser.js';

export function generateValidatorFile(schema: ParsedSchema): string {
  const messageName = schema.fileName.replace('.json', '');
  // Strip meta-schema fields that cause AJV 8 compatibility issues
  // AJV 8 does not support Draft-04 "id" field (use "$id" instead) and
  // complains about "$schema" when the referenced meta-schema is not loaded
  const cleanedSchema = { ...schema.rawSchema } as Record<string, unknown>;
  delete cleanedSchema['$schema'];
  delete cleanedSchema['id'];
  const schemaJson = JSON.stringify(cleanedSchema, null, 2);

  const lines: string[] = [];

  lines.push(`import type { ValidateFunction } from 'ajv';`);
  lines.push(`import { ajv } from './_ajv.js';`);
  lines.push('');
  lines.push(`const schema = ${schemaJson} as const;`);
  lines.push('');
  lines.push(`export const validate${messageName}: ValidateFunction = ajv.compile(schema);`);

  return lines.join('\n') + '\n';
}

export function generateAjvSetupFile(): string {
  const lines: string[] = [];

  lines.push(`// @ts-nocheck`);
  lines.push(`// Auto-generated by @evtivity/codegen - CJS/ESM interop requires ts-nocheck`);
  lines.push(`import Ajv from 'ajv';`);
  lines.push(`import addFormats from 'ajv-formats';`);
  lines.push('');
  lines.push(`const ajv = new Ajv({`);
  lines.push(`  allErrors: true,`);
  lines.push(`  strict: false,`);
  lines.push(`  validateSchema: false,`);
  lines.push(`});`);
  lines.push('');
  lines.push(`addFormats(ajv);`);
  lines.push('');
  lines.push(`export { ajv };`);

  return lines.join('\n') + '\n';
}
